name: test
on:
  push:
    branches:
    - "**"
  pull_request: {}
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macOS-latest
        - windows-latest
        parallelism: [3]
        index: [0,1,2]
    steps:
    - name: setup go
      uses: actions/setup-go@v2
    - name: checkout
      uses: actions/checkout@v2
    - name: test
      run: |
        curl -sfL https://raw.githubusercontent.com/Songmu/gotesplit/master/install.sh | sh -s
        bin/gotesplit -total ${{ matrix.parallelism }} -index ${{ matrix.index }} ./...
